"""'a'

Revision ID: 96440d7499cb
Revises: 
Create Date: 2019-11-17 14:17:15.718949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96440d7499cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaders',
    sa.Column('field1', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Team', sa.Text(), nullable=True),
    sa.Column('Gamesplayed', sa.Integer(), nullable=True),
    sa.Column('AverageMin', sa.Float(), nullable=True),
    sa.Column('FGM', sa.Float(), nullable=True),
    sa.Column('FGA', sa.Float(), nullable=True),
    sa.Column('FG%', sa.Float(), nullable=True),
    sa.Column('3PM', sa.Float(), nullable=True),
    sa.Column('3ATT', sa.Float(), nullable=True),
    sa.Column('3PT%', sa.Float(), nullable=True),
    sa.Column('FTM', sa.Float(), nullable=True),
    sa.Column('FTA', sa.Float(), nullable=True),
    sa.Column('FT%', sa.Float(), nullable=True),
    sa.Column('OREB', sa.Float(), nullable=True),
    sa.Column('DREB', sa.Float(), nullable=True),
    sa.Column('REB', sa.Float(), nullable=True),
    sa.Column('AST', sa.Float(), nullable=True),
    sa.Column('STL', sa.Float(), nullable=True),
    sa.Column('BLK', sa.Float(), nullable=True),
    sa.Column('TOV', sa.Float(), nullable=True),
    sa.Column('PPG', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('field1')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('pic', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('json_id', sa.Integer(), nullable=True),
    sa.Column('pict', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('players_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('gamesplayed', sa.Integer(), nullable=True),
    sa.Column('averageMin', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('fgpct', sa.Float(), nullable=True),
    sa.Column('treepm', sa.Float(), nullable=True),
    sa.Column('treeatt', sa.Float(), nullable=True),
    sa.Column('treepct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('ftpct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Float(), nullable=True),
    sa.Column('dreb', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['players_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('news')
    op.drop_table('leaders')
    op.drop_table('daily')
    # ### end Alembic commands ###
